name: nlp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - pip:
      - torch
      - transformers
      - datasets
      - accelerate
      - sentencepiece
      - protobuf
      - lxml
      - bs4
