CHARGES = {
    "compute_vm_fee": {
        "description": "Charge for running virtual machines based on vCPU, memory, OS, and commitment.",
        "variables": ["vcpu_count", "memory_gb", "os_type", "vm_family", "usage_hours", "region", "spot_instance", "commitment_term"],
        "synonyms": ["vm runtime charge", "compute instance fee", "virtual machine cost"],
    },
    "gpu_compute_fee": {
        "description": "Charge for GPU-enabled compute usage.",
        "variables": ["gpu_type", "gpu_count", "usage_hours", "region", "os_type"],
        "synonyms": ["gpu instance fee", "accelerator charge", "gpu runtime cost"],
    },
    "managed_disk_fee": {
        "description": "Charge for managed disks based on type, size, and count.",
        "variables": ["disk_type", "disk_size_gb", "managed_disk_count", "region"],
        "synonyms": ["disk charge", "managed storage fee", "block storage cost"],
    },
    "data_egress_fee": {
        "description": "Charge for data leaving Azure regions.",
        "variables": ["data_egress_gb", "region"],
        "synonyms": ["egress charge", "outbound data fee", "data transfer out"],
    },
    "data_ingress_fee": {
        "description": "Charge for data entering Azure regions where applicable.",
        "variables": ["data_ingress_gb", "region"],
        "synonyms": ["ingress charge", "inbound data fee", "data transfer in"],
    },
    "storage_transaction_fee": {
        "description": "Charge for storage account transactions and redundancy level.",
        "variables": ["storage_transactions_millions", "redundancy", "region"],
        "synonyms": ["storage ops fee", "transaction charge", "storage request cost"],
    },
    "public_ip_fee": {
        "description": "Charge for public IP addresses allocated.",
        "variables": ["public_ip_count", "region"],
        "synonyms": ["ip address charge", "public ip cost", "elastic ip fee"],
    },
    "load_balancer_fee": {
        "description": "Charge for load balancer rules and tier.",
        "variables": ["load_balancer_rules", "service_tier", "region"],
        "synonyms": ["lb fee", "balancer charge", "traffic distribution cost"],
    },
    "aks_cluster_fee": {
        "description": "Charge for AKS clusters based on node count and type.",
        "variables": ["kubernetes_node_count", "kubernetes_node_type", "vm_family", "region"],
        "synonyms": ["kubernetes fee", "aks charge", "container cluster cost"],
    },
    "function_app_fee": {
        "description": "Charge for serverless executions and execution time.",
        "variables": ["function_executions", "function_exec_ms", "region"],
        "synonyms": ["faas charge", "functions cost", "serverless fee"],
    },
    "sql_database_fee": {
        "description": "Charge for Azure SQL based on vCores, storage, and retention.",
        "variables": ["sql_vcores", "sql_storage_gb", "backup_retention_days", "service_tier", "region"],
        "synonyms": ["sql charge", "database fee", "sql managed instance cost"],
    },
    "snapshot_storage_fee": {
        "description": "Charge for snapshot storage volume and redundancy.",
        "variables": ["snapshot_gb", "redundancy", "region"],
        "synonyms": ["snapshot fee", "backup snapshot cost", "image snapshot charge"],
    },
    "app_service_fee": {
        "description": "Charge for App Service instances and tier.",
        "variables": ["app_service_instances", "service_tier", "region"],
        "synonyms": ["app service charge", "web app fee", "app hosting cost"],
    },
}

VARIABLES = {
    "region": {
        "dtype": str,
        "values": ["uk_south", "uk_west", "westeurope", "northeurope", "eastus", "westus2"],
        "units": "region",
        "description": "Azure region where resources are deployed",
        "alternative_names": ["location", "geo_region"],
    },
    "vm_family": {
        "dtype": str,
        "values": ["Dsv5", "Esv5", "Fsv2", "Lsv3", "NCasT4_v3"],
        "units": "family",
        "description": "Virtual machine family that defines CPU and memory profile",
        "alternative_names": ["vm series", "instance family"],
    },
    "os_type": {
        "dtype": str,
        "values": ["linux", "windows"],
        "units": "os",
        "description": "Operating system for the compute workload",
        "alternative_names": ["operating_system", "guest_os"],
    },
    "usage_hours": {
        "dtype": float,
        "values": (0.0, 744.0),
        "units": "hours",
        "description": "Total runtime in hours over the billing window",
        "alternative_names": ["runtime_hours", "billable_hours"],
    },
    "vcpu_count": {
        "dtype": int,
        "values": (1, 128),
        "units": "vCPUs",
        "description": "Number of virtual CPUs allocated",
        "alternative_names": ["cpu_count", "virtual_cores"],
    },
    "memory_gb": {
        "dtype": float,
        "values": (1.0, 2048.0),
        "units": "GiB",
        "description": "Amount of memory allocated to the instance",
        "alternative_names": ["ram_gb", "memory_size"],
    },
    "gpu_type": {
        "dtype": str,
        "values": ["T4", "A10", "A100", "MI300X"],
        "units": "gpu type",
        "description": "Type of GPU accelerator",
        "alternative_names": ["accelerator_type", "graphics_processor"],
    },
    "gpu_count": {
        "dtype": int,
        "values": (0, 8),
        "units": "GPUs",
        "description": "Number of GPUs attached to the instance",
        "alternative_names": ["accelerator_count", "gpu_units"],
    },
    "disk_type": {
        "dtype": str,
        "values": ["standard_hdd", "standard_ssd", "premium_ssd", "ultra_ssd"],
        "units": "disk type",
        "description": "Managed disk performance tier",
        "alternative_names": ["storage_type", "disk_tier"],
    },
    "disk_size_gb": {
        "dtype": int,
        "values": (30, 32768),
        "units": "GB",
        "description": "Size of each managed disk",
        "alternative_names": ["disk_capacity_gb", "volume_size_gb"],
    },
    "managed_disk_count": {
        "dtype": int,
        "values": (0, 64),
        "units": "disks",
        "description": "Count of managed disks attached",
        "alternative_names": ["disk_count", "num_disks"],
    },
    "data_egress_gb": {
        "dtype": float,
        "values": (0.0, 100000.0),
        "units": "GB",
        "description": "Outbound data transferred from Azure",
        "alternative_names": ["egress_gb", "data_transfer_out_gb"],
    },
    "data_ingress_gb": {
        "dtype": float,
        "values": (0.0, 100000.0),
        "units": "GB",
        "description": "Inbound data transferred to Azure",
        "alternative_names": ["ingress_gb", "data_transfer_in_gb"],
    },
    "storage_transactions_millions": {
        "dtype": float,
        "values": (0.0, 500.0),
        "units": "million tx",
        "description": "Number of storage account operations in millions",
        "alternative_names": ["storage_ops_million", "tx_millions"],
    },
    "public_ip_count": {
        "dtype": int,
        "values": (0, 100),
        "units": "IPs",
        "description": "Number of public IP addresses allocated",
        "alternative_names": ["ip_count", "public_ips"],
    },
    "load_balancer_rules": {
        "dtype": int,
        "values": (0, 200),
        "units": "rules",
        "description": "Configured load balancer rules",
        "alternative_names": ["lb_rules", "balancer_rules"],
    },
    "kubernetes_node_count": {
        "dtype": int,
        "values": (0, 1000),
        "units": "nodes",
        "description": "Number of AKS nodes in the cluster",
        "alternative_names": ["aks_nodes", "cluster_nodes"],
    },
    "kubernetes_node_type": {
        "dtype": str,
        "values": ["system", "user", "spot"],
        "units": "node type",
        "description": "AKS node pool type",
        "alternative_names": ["node_pool_type", "aks_node_class"],
    },
    "spot_instance": {
        "dtype": str,
        "values": ["true", "false"],
        "units": "flag",
        "description": "Whether the compute uses spot capacity",
        "alternative_names": ["spot_flag", "preemptible"],
    },
    "commitment_term": {
        "dtype": str,
        "values": ["none", "1yr", "3yr"],
        "units": "term",
        "description": "Savings commitment for compute resources",
        "alternative_names": ["reservation_term", "commit_term"],
    },
    "service_tier": {
        "dtype": str,
        "values": ["basic", "standard", "premium", "isolated"],
        "units": "tier",
        "description": "Service tier for managed services",
        "alternative_names": ["pricing_tier", "sku_tier"],
    },
    "function_executions": {
        "dtype": int,
        "values": (0, 1000000000),
        "units": "invocations",
        "description": "Number of serverless function calls",
        "alternative_names": ["invocations", "function_calls"],
    },
    "function_exec_ms": {
        "dtype": float,
        "values": (0.1, 600000.0),
        "units": "ms",
        "description": "Average or billed execution time per invocation",
        "alternative_names": ["exec_time_ms", "duration_ms"],
    },
    "sql_vcores": {
        "dtype": int,
        "values": (0, 128),
        "units": "vCores",
        "description": "vCore count for Azure SQL",
        "alternative_names": ["db_vcores", "sql_cores"],
    },
    "sql_storage_gb": {
        "dtype": int,
        "values": (0, 8192),
        "units": "GB",
        "description": "Allocated storage for Azure SQL",
        "alternative_names": ["db_storage_gb", "sql_capacity_gb"],
    },
    "backup_retention_days": {
        "dtype": int,
        "values": (0, 365),
        "units": "days",
        "description": "Backup retention period for databases",
        "alternative_names": ["retention_days", "backup_days"],
    },
    "snapshot_gb": {
        "dtype": float,
        "values": (0.0, 100000.0),
        "units": "GB",
        "description": "Total snapshot storage size",
        "alternative_names": ["snapshot_size_gb", "image_snapshot_gb"],
    },
    "app_service_instances": {
        "dtype": int,
        "values": (0, 200),
        "units": "instances",
        "description": "Count of App Service instances",
        "alternative_names": ["app_instances", "webapp_instances"],
    },
    "redundancy": {
        "dtype": str,
        "values": ["LRS", "ZRS", "GRS", "GZRS"],
        "units": "redundancy",
        "description": "Storage redundancy configuration",
        "alternative_names": ["replication", "redundancy_mode"],
    },
    "support_plan": {
        "dtype": str,
        "values": ["none", "developer", "standard", "professional_direct"],
        "units": "plan",
        "description": "Azure support plan level",
        "alternative_names": ["support_level", "support_tier"],
    },
}
